# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af42e8144ce7856a6aba0082bc7acc6b47f42e9be11a6bed11c4e59b9dd04c0bb25fe37fd576a43d889c656e1c7e697920ed4944311c3b31711d4f68174f6503

test:
  secret_key_base: cd2b30873756233c4911a905de7dc9ab1fb0d5cf68cf28d6e95da0bfa4f80688f26209f28d5407510466db497590f0b83d9207c23388b86989ec8d044ac2295e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
